FROM httpd:2.4.25

MAINTAINER Philip Schmid

# Install some useful tools for debugging purposes
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		vim \
    less \
    net-tools \
    locate \
    libapache2-mod-php5 \
	  && rm -r /var/lib/apt/lists/*

# Copy the required files, scripts and configurations to image
COPY apache_mshield_reverse_proxy /usr/local/bin/
RUN chmod +x /usr/local/bin/apache_mshield_reverse_proxy

RUN rm -f /usr/local/apache2/htdocs/index.html
COPY htdocs/* /usr/local/apache2/htdocs/

RUN rm -f /usr/local/apache2/conf/httpd.conf
COPY conf/httpd.conf /usr/local/apache2/conf/
COPY conf/mime.types /usr/local/apache2/conf/
COPY conf/extra/httpd-ssl.conf /usr/local/apache2/conf/extra/
COPY conf/extra/httpd-preauth.conf /usr/local/apache2/conf/extra/
COPY conf/extra/mod_mshield_url_rating.conf /usr/local/apache2/conf/extra/
COPY conf/extra/proxy-html.conf /usr/local/apache2/conf/extra/

COPY mod_mshield.so /usr/local/apache2/modules/

# Start the apache service
EXPOSE 80
EXPOSE 443

CMD ["apache_mshield_reverse_proxy"]
